external_components:
  - source: github://ananyevgv/esphome-components/
    components: [ cg_anem ]

sensor:
- platform: cg_anem
  ambient_temperature:
    name: "Ambient temperature"
  hotend_temperature:
    name: "Hotend temperature"
  heat_power:
    name: "Heat power"
  air_consumption:
    name: "Air consumption"
  air_flow_rate:
    name: "Air flow rate"
  firmware_version:
    name: "Firmware version"
  min_air_flow_rate:
    name: "Min air flow rate"
  max_air_flow_rate:
    name: "Max air flow rate"
  address: 0x11
  duct: 105
  update_interval: 10s

binary_sensor:
  status_up:
    name: "UNSTEADY PROCESS"
  status_uv:
    name: "OVERVOLTAGE"
  status_wdt:
    name: "WATCHDOG TIMER"
